import protocols from "@/data/protocols.json";
import type {ChainId,WalletProfile} from "@/types";
import {getBalances} from "./alchemy";import {getNftTransfers,getTokenTransfers,getTransactions} from "./etherscan";import {resolveEns} from "./ens";import {getCached} from "@/lib/db/cache";
const DAY=86400;
function empty(address:string):WalletProfile{return {address,ensName:null,chainsActive:[],firstTxTimestamp:0,lastTxTimestamp:0,walletAgeDays:0,totalTxCount:0,distinctActiveMonths:0,txsPerActiveMonth:0,swapCount:0,uniqueTokensTraded:0,dexProtocolsUsed:[],protocolsTouched:[],protocolCategories:[],deepestProtocolTxCount:0,nftTxCount:0,uniqueCollections:0,currentHoldings:[],totalUsdValue:0,holdingsCount:0,longestContinuousHoldDays:0,medianHoldDurationTop5Days:0,pctPortfolioUntouched90d:0,sellToBuyRatio:0,memecoinVolumeShare:0,leverageProtocolTxCount:0,newContractInteractionCount:0,openApprovalCount:0}}
export async function buildWalletProfile(address:string):Promise<WalletProfile>{
 const now=Math.floor(Date.now()/1000);const chains:ChainId[]=[1,8453];const sets=await Promise.all(chains.map(async chain=>{const [tx,token,nft,holdings]=await Promise.all([getCached(`${address}:${chain}:tx`,24,()=>getTransactions(address,chain)),getCached(`${address}:${chain}:token`,24,()=>getTokenTransfers(address,chain)),getCached(`${address}:${chain}:nft`,24,()=>getNftTransfers(address,chain)),getCached(`${address}:${chain}:balances`,24,()=>getBalances(address,chain))]);return {chain,tx,token,nft,holdings}}));
 const all=sets.flatMap(s=>s.tx);if(!all.length){const result=empty(address);result.ensName=await resolveEns(address);return result}const times=all.map(x=>Number(x.timeStamp)||0).filter(Boolean).sort((a,b)=>a-b);const labelMap=new Map(protocols.map(p=>[`${p.chainId}:${p.address.toLowerCase()}`,p]));const touched=sets.flatMap(s=>s.tx.map(t=>labelMap.get(`${s.chain}:${(t.to||"").toLowerCase()}`))).filter((x):x is (typeof protocols)[number]=>Boolean(x));const months=new Set(times.map(t=>new Date(t*1000).toISOString().slice(0,7)));const token=sets.flatMap(s=>s.token),nfts=sets.flatMap(s=>s.nft),holdings=sets.flatMap(s=>s.holdings);const buys=token.filter(t=>t.to.toLowerCase()===address).length,sells=token.filter(t=>t.from.toLowerCase()===address).length;
 return {address,ensName:await resolveEns(address),chainsActive:sets.filter(s=>s.tx.length).map(s=>s.chain),firstTxTimestamp:times[0],lastTxTimestamp:times.at(-1)||0,walletAgeDays:Math.floor((now-times[0])/DAY),totalTxCount:all.length,distinctActiveMonths:months.size,txsPerActiveMonth:all.length/Math.max(1,months.size),swapCount:touched.filter(x=>x.category==="dex").length,uniqueTokensTraded:new Set(token.map(x=>(x.contractAddress||"").toLowerCase())).size,dexProtocolsUsed:[...new Set(touched.filter(x=>x.category==="dex").map(x=>x.protocol))],protocolsTouched:[...new Set(touched.map(x=>x.protocol))],protocolCategories:[...new Set(touched.map(x=>x.category))],deepestProtocolTxCount:Math.max(0,...touched.map(p=>touched.filter(x=>x.protocol===p.protocol).length)),nftTxCount:nfts.length,uniqueCollections:new Set(nfts.map(x=>x.contractAddress)).size,currentHoldings:holdings,totalUsdValue:holdings.reduce((n,h)=>n+h.usdValue,0),holdingsCount:holdings.length,longestContinuousHoldDays:Math.floor((now-times[0])/DAY),medianHoldDurationTop5Days:Math.floor((now-times[Math.floor(times.length/2)])/DAY),pctPortfolioUntouched90d:holdings.length?holdings.filter(h=>!h.lastMovedTs||now-h.lastMovedTs>90*DAY).length/holdings.length:0,sellToBuyRatio:sells/Math.max(1,buys),memecoinVolumeShare:token.filter(t=>/PEPE|DOGE|SHIB|MEME/i.test(t.tokenSymbol||"")).length/Math.max(1,token.length),leverageProtocolTxCount:touched.filter(x=>x.category==="derivatives").length,newContractInteractionCount:new Set(all.map(x=>x.to).filter(Boolean)).size,openApprovalCount:all.filter(x=>x.input?.startsWith("0x095ea7b3")).length};
}
